name: Build SpotiClone APK

on:
  workflow_dispatch: 

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build inside Buildozer Container
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: pip3 install --user --upgrade Cython==0.29.33 virtualenv; buildozer android debug
          buildozer_version: master

      - name: Upload the Finished App
        uses: actions/upload-artifact@v4
        with:
          name: SpotiClone-APK
          path: bin/*.apk
          
